version: '3' #docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project dir with container web dir
    ports:
      - 8060:80
      - 443:443 #for future sll traffic

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=php_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_HOST=3306